In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.33099834, 0.08007032, 0.86868831, 0.24296506, 0.45252952])

In [16]:
np.random.rand(5,5)

array([[0.33752836, 0.48008538, 0.37347428, 0.89303072, 0.14827663],
       [0.46136184, 0.61512541, 0.57087831, 0.92562387, 0.00880728],
       [0.09725025, 0.64636524, 0.47420566, 0.43029065, 0.55789414],
       [0.84781631, 0.92016142, 0.89067744, 0.16108476, 0.64699726],
       [0.89192696, 0.23468785, 0.78613882, 0.5780219 , 0.47094016]])

In [17]:
np.random.randn(5)

array([-0.31562852, -2.10199318,  0.94650372, -0.93857746, -0.39620027])

In [18]:
np.random.randint(1,100,10)

array([86, 30, 70, 21, 10,  4, 61, 43, 44, 43])

In [19]:
arr = np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0,50,10)

In [22]:
ranarr

array([16,  3, 18, 23,  1, 24, 33, 34, 40, 19])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

40

In [25]:
ranarr.min()

1

In [26]:
ranarr

array([16,  3, 18, 23,  1, 24, 33, 34, 40, 19])

In [27]:
ranarr.argmax()

8

In [28]:
ranarr.argmin()

4

In [29]:
arr.shape

(25,)

In [30]:
arr = arr.reshape(5,5)

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.shape

(5, 5)

In [33]:
arr.dtype

dtype('int32')

In [34]:
import numpy as np

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[8]

8

In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [39]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[0:5] = 100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_array = arr[0:6]

In [47]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [48]:
slice_of_array[:] = 99

In [49]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [50]:
arr_copy = arr.copy()

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
arr_copy[:] = 100

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[0][0]

5

In [57]:
arr_2d[1][1]

25

In [58]:
arr_2d[2,2]

45

In [59]:
arr_2d[:2,2:]

array([[15],
       [30]])

In [60]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [61]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [62]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[arr<4]

array([1, 2, 3])

In [68]:
arr_2d = np.arange(50).reshape(5,10)

In [69]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [71]:
arr_2d[1:3,3:4]

array([[13],
       [23]])

In [72]:
import numpy as np

(array with array) (array with scalars) (universal array functions)

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [76]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [78]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [79]:
arr / arr

C:\Users\Admin\AppData\Local\Temp/ipykernel_3528/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [81]:
arr + arr + arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [82]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [83]:
10 - 10

0

In [84]:
arr % arr

C:\Users\Admin\AppData\Local\Temp/ipykernel_3528/2907441788.py:1: RuntimeWarning: divide by zero encountered in remainder
  arr % arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [85]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
arr / arr

C:\Users\Admin\AppData\Local\Temp/ipykernel_3528/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [88]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [90]:
np.max(arr)

10

In [91]:
np.min(arr)

0

In [92]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [93]:
np.log(arr)

C:\Users\Admin\AppData\Local\Temp/ipykernel_3528/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [94]:
import numpy as np

In [95]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [98]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [99]:
np.ones(10)*4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [101]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [102]:
arr = np.arange(10,51,2)

In [103]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [107]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
arr = np.arange(3,3)

In [109]:
arr

array([], dtype=int32)

In [113]:
arr = np.arange(0,9).reshape

In [114]:
arr

<function ndarray.reshape>

In [115]:
my_mat = [[0,1,2],[3,4,5],[6,7,8]]

In [116]:
np.array(my_mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.random.rand(1)

array([0.84760188])

In [120]:
np.random.randn(25)

array([-0.09399341,  2.04535146,  0.1187544 , -0.64865643,  0.76321682,
        1.08475707, -1.59869995,  0.05129015, -1.49315499,  0.00581324,
       -1.68870025,  2.77183285,  1.67654324, -1.37839759,  0.57997345,
        0.14998018,  1.26066968, -1.12054458,  0.72888493,  1.14497219,
        0.33399138, -1.54528146, -0.0448464 ,  1.51760657, -0.14228631])

In [121]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [123]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])